### ISSUE TITLE
Set Fbx as default?

### ISSUE THREAD

**Issue by tomonorman** [art-e-fact/RoboProp#102]
Do we default roboprop models to fbx rather than obj

Should fix texture issues, but only works with harmonic(?)

@fabid FYI, are we set on only using harmonic if gazebo? I guess we are with things like conveyor belts

**Comment by fabid** [comment]
Since I didn't know about fbx

> fbx are like OBJ in that it contains 3D object data; however, it also contains animation data. This makes this file type most popular in film, gaming, and VFX—all industries that need complex models, materials, and animation. This file format is owned by Autodesk and supported widely in both VFX and game engines.

if compatibility is high, that sounds good

While some people seem to have texture pathing issues with fbx and isaac, it seems to be supported by isaac overall https://forums.developer.nvidia.com/t/isaac-sim-import-fbx-but-no-textures/241110

So I would say yes

**Comment by tomonorman** [comment]
Closed with #103
