### ISSUE TITLE
conveyor belt?

### ISSUE THREAD

**Issue by fabid** [art-e-fact/RoboProp#75]

**Comment by fabid** [comment]
@tomonorman you mentioned you added a model to roboprop, is it this one?

How do we deal with the animation in gazebo? I think we need to add a Plugin to the model. Do we manage that in the model stored on roboprop, or shall we add it later, at behavior generatio stage

![Image](https://github.com/art-e-fact/RoboProp/assets/2442821/8483e9a1-8030-4a85-b523-78c51bcc1a33)

**Comment by tomonorman** [comment]
Might be better to add it in at behaviour generation? (Unless we can use that plugin to also do the animation in simbuilder)
@azazdeaz any thoughts?

**Comment by azazdeaz** [comment]
I did some experiment and it seems very promising. I don't want to celebrate prematurely, but it seems like the conveyor belt will work nicely, and so far the track simulation on the CuGo looks promising. 
https://github.com/art-e-fact/robostage-simbuilder/pull/50
I'll try to finish this PR and create demos this week.

**Comment by azazdeaz** [comment]
[Screencast from 2023-12-19 10:36:20.webm](https://github.com/art-e-fact/RoboProp/assets/2298371/420b5c15-3400-43d7-bc6c-2c4549fc97bf)

This is a  "conveyor belt" test. The planes are carrying the cubes into a fixed direction.

**Comment by fabid** [comment]
Nice conveyor belt demo

**Comment by fabid** [comment]
@azazdeaz How will we specify  the conveyor belt surface? Could we make it in a way that is roughly compatible with the track plugin of gazebo?

**Comment by azazdeaz** [comment]
Yes, the API should be almost the same as the Gazebo plugin.
These are the Gazebo examples for reference:
 - https://github.com/gazebosim/gz-sim/blob/gz-sim8/examples/worlds/conveyor.sdf
 - https://github.com/gazebosim/gz-sim/blob/gz-sim8/examples/worlds/tracked_vehicle_simple.sdf

**Comment by tomonorman** [comment]
Closing as Conveyor Belt introduced in Robostage
