### ISSUE TITLE
roboprop UI feedback durin blender conversion

### ISSUE THREAD

**Issue by tomonorman** [art-e-fact/RoboProp#88]

**Comment by fabid** [comment]
@tomonorman have you started working on it? if not, maybe it can wait later, as not directly needed in the new cycle scope

**Comment by tomonorman** [comment]
In a sense yes, the move to workers and celery (and the debugging before that) originally came from wanting to do this.

Roboprop is fixed now (in the sense it works), but there is little feedback (just a message saying "conversion started").

If possible, just want to do a simple "started"->"finished"/"failed", which would involve doing some polling of the task. Dont think it will take that long / can do it whenever I have a moment. But if not directly required hold also.

Perhaps keep it as issue, but not move over to new project cycle?

**Comment by fabid** [comment]
ok, let's finissh this then!
